// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt(arg1, arg2) {
  return window['go']['main']['App']['Decrypt'](arg1, arg2);
}

export function Encrypt(arg1, arg2) {
  return window['go']['main']['App']['Encrypt'](arg1, arg2);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}
