// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt(arg1:string,arg2:string):Promise<string>;

export function Encrypt(arg1:string,arg2:string):Promise<string>;

export function OpenFile():Promise<string>;

export function Save(arg1:string):Promise<string>;
